# -*- coding: utf-8 -*-
"""rock-paper-scissors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAVJJ_zE0CZ3dGYyUfOT2KQnoobX5NdS
"""

import random

# Ask for player name
name = input("Enter your name: ")

# Choices for the game
choices = ["rock", "paper", "scissors"]

# Score tracking
user_score = 0
computer_score = 0
rounds_played = 0

print(f"Welcome, {name}! Type 'exit' to quit the game.")

while True:
    # Get user choice
    user_choice = input("Choose rock, paper, or scissors: ").lower()

    # Check if user wants to exit
    if user_choice == "exit":
        break

    # Validate choice
    if user_choice not in choices:
        print("Invalid choice! Try again.")
        continue

    # Computer makes a random choice
    computer_choice = random.choice(choices)
    print(f"Computer chose: {computer_choice}")

    # Decide who wins
    if user_choice == computer_choice:
        print("It's a draw!")
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "paper" and computer_choice == "rock") or \
         (user_choice == "scissors" and computer_choice == "paper"):
        print("] You win this round!")
        user_score += 1
    else:
        print(" You lost this round.")
        computer_score += 1

    rounds_played += 1
    print(f"Score — You: {user_score} | Computer: {computer_score}\n")

# Final message
print(f"\nGame over! You played {rounds_played} rounds.")
print(f"Final score — You: {user_score} | Computer: {computer_score}")

# Save score to file
with open("score_log.txt", "a") as file:
    file.write(f"{name} played {rounds_played} rounds |4ggffghfgh Final Score — You: {user_score}, Computer: {computer_score}\n")